name: deploy frontend

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: uberspace
      url: https:/www.wunderundfitzig.de

    steps:
      - uses: actions/checkout@v3

      - name: Set backend user env variables
        run: |
          echo "" >> .env
          echo "BACKEND_USER=$BACKEND_USER" >> .env
          echo "BACKEND_PASSWORD=$BACKEND_PASSWORD" >> .env
        env:
          BACKEND_USER: ${{ secrets.BACKEND_USER }}
          BACKEND_PASSWORD: ${{ secrets.BACKEND_PASSWORD }}

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_SSH_DEPLOY_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "frontend/"
          EXCLUDE: ".vscode, .env.local.example, .eslintrc.json, .gitignore, .prettierignore, .prettierrc, README.md"
          REMOTE_HOST: wfweb.uber.space
          REMOTE_USER: wfweb
          TARGET: "wundf-website"

      - name: Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: wfweb.uber.space
          username: wfweb
          key: ${{ secrets.PRIVATE_SSH_DEPLOY_KEY }}
          script: |
            npm ci
            npm run build
            supervisorctl restart wundf-website
