name: deploy cms (cms.wunderundfitzig.de)

on:
  push:
    branches:
      - main
      - dev
    paths:
      - backend/**
      - .github/workflows/deploy-cms.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: cms/production
      url: https://cms.wunderundfitzig.de

    steps:
      - uses: actions/checkout@v3

      # - uses: php-actions/composer@v6
      #   with:
      #     php_extensions: gd
      #     dev: no
      #     args: --working-dir backend

      - name: Create .env file
        working-directory: backend
        run: |
          echo "ENVIRONMENT=production" >> .env

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_SSH_DEPLOY_KEY }}
          ARGS: "-rltgoDzvO --delete --exclude-from=backend/.deployignore"
          SOURCE: "backend/"
          REMOTE_HOST: wfweb.uber.space
          REMOTE_USER: wfweb
          TARGET: "html"
