name: deploy frontend

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: uberspace
      url: https:/www.wunderundfitzig.de

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Install npm dependencies
        run: npm ci

      - name: Set backend user env variables
        run: |
          echo "" >> .env
          echo "BACKEND_USER=$BACKEND_USER" >> .env
          echo "BACKEND_PASSWORD=$BACKEND_PASSWORD" >> .env
        env:
          BACKEND_USER: ${{ secrets.BACKEND_USER }}
          BACKEND_PASSWORD: ${{ secrets.BACKEND_PASSWORD }}

      - name: Run build task
        run: npm run build

      - name: Create deploy folder
        run: |
          mkdir deploy
          cp -a .next ./deploy
          cp package.json ./deploy
          cp next.config.js ./deploy
          cp .env ./deploy
          cp -a node_modules ./deploy
          cp -a public ./deploy

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_SSH_DEPLOY_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "frontend/deploy/"
          REMOTE_HOST: wfweb.uber.space
          REMOTE_USER: wfweb
          TARGET: "wundf-website"

      - name: Restart Server
        uses: appleboy/ssh-action@0.1.10
        with:
          host: wfweb.uber.space
          username: wfweb
          key: ${{ secrets.PRIVATE_SSH_DEPLOY_KEY }}
          script: |
            supervisorctl restart wundf-website
